### PR TITLE
Add rule: `"arrow-parens": [2, "as-needed"]`

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
The history of this seems that an identical PR was submitted as #15 almost one year ago.

There was some discussion in https://github.com/feross/standard/issues/309.

In February 5, this rule was merged in but with the "always" option, as https://github.com/feross/eslint-config-standard/commit/dd85d36d41530deac9c6036f79116f9e21966235 and released in v5.

In March 24, this rule was removed via #28.

It is now October 23 and the reasonable code style seems to me to be "arrow-parens" with "as-needed".

**Comment by mightyiam** [comment]
http://eslint.org/docs/rules/arrow-parens

**Comment by mightyiam** [comment]
Is this a hot potato, or something? I've posted this PR 25 days ago and no comments :zipper_mouth_face: ...

**Comment by feross** [comment]
I don't think anything has changed since this rule was removed, so why add it back now?

**Comment by mightyiam** [comment]
@feross I'm not suggesting the same format! The rule was added with "always" and then removed. I'm suggesting "as-needed", which makes total sense to me. Doesn't it to you?

`n => n + 1` vs. `(n) => n + 1`: the parens are totally unnecessary. Why include them?
I'm the biggest advocate of standard because of the reasonable choices. Here, at least to me, seems to be an obvious one.

Even though I've seen contributors convinced (#309) that "always" is the correct choice, because of consistency, I disagree and I feel that "as-needed" is correct.

1. in some cases, where the argument is one character (e.g. `n => n + 1`), this means three times more characters on the left side of the function.
1. Lambda functions are cool. `n = n + 1` looks nice to me.
1. Consistency with other syntaxes is not an argument, because different syntaxes of the arrow function serve different purposes. In those different purposes, it is legitimate to use those different syntaxes. In the case of a one-liner, there is no question about it, in my mind and I think that this is the majority of JavaScript developers: no parens. In the case of a single argument and a multi-line code block, it is debatable. Yet, it is our duty to close the debate. I think that setting a rule that is somewhere between "as-needed" and "always" would be too complicated to to justify, for people to accept. And that's besides my personal preference for "always". I'll not be comfortable explaining that "only for one-liners you may omit the parens", just as I'll not be comfortable explaining that "for consistency, even though JS allows omitting it, you may not omit it".
1. "as-needed" needs no explaining. That's the beauty. "as needed"—bang. Simple, tried and tested.

**Comment by dcousens** [comment]
@mightyiam maybe you should post this to https://github.com/feross/standard/issues/309 instead

**Comment by mightyiam** [comment]
# Next step on arrow-function parens

We are software developers. We do things incrementally, while understanding also the bigger picture.

Thus my intention in this conversation is to converge on a single next step; a single and simple rule that everyone agrees on.

## Background

1. Oct 26, 2015 #309: initial suggestion
1. Oct 27, 2015 https://github.com/feross/eslint-config-standard/pull/15: PR suggesting `arrow-parens` "as-needed" (closed)
1. Feb 5 2016 https://github.com/feross/eslint-config-standard/commit/dd85d36d41530deac9c6036f79116f9e21966235: `arrow-parens` "always" added in time for v6.
1. Feb 10 2016 #414: discussion flollowing release of v6 with `arrow-parens` "always"
1. Mar 24 2016 https://github.com/feross/eslint-config-standard/pull/28: `arrow-parens` "always" removed in time for v7
1. Oct 23 2016 https://github.com/feross/eslint-config-standard/pull/54: PR for `arrow-parens` "as-needed" again (by me) (closed)

## Arrow function with no arguments: parens or placeholder

JavaScript syntax requires parens. But, there's a workaround:

```js
items.forEach(_ => console.log('Item!'))
```

We declare an argument with the intention of not using it, just because we find it easier to type and/or read `_` than `()` in this context. Note that instead of `_` the placeholder can be anything that Standard will approve of (`🦄` seems to not be allowed).

For the sake of moving forward with decision regarding parens for arrow functions, I suggest that we choose to postpone conversation regarding this workaround. Even though we have the intention of setting each rule once for all eternity, and even though these two matters are somewhat coupled, and even though ignoring this now might mean that it will be harder to get agreement on later, I feel that it is better to leave this for later. Also because even if it is later Standardized as `_` or `()`, it seems to me like an easy and auto-fixable change.

## Arrow function with a single argument

### Parens required

* The first end of the spectrum
* [Already implemented in ESLint](http://eslint.org/docs/rules/arrow-parens#as-needed)
* Easy to explain and understand
* Minimalism over consistency (consistency with zero and multiple arguments)

### Parens disallowed

* The second end of the spectrum
* [Already implemented in ESLint](http://eslint.org/docs/rules/arrow-parens#always)
* Easiest to explain and understand
* Consistency over minimalism (consistency with zero and multiple arguments)

### Parens when body is multi-line

This means that when the body of a single-argument arrow function is multi-line, parens are required.

* What is the purpose for this? No judgement intended.
* I don't know of an implementation

## Arrow function with multiple arguments :white_check_mark:

JavaScript syntax chooses for us. Parens required.

## Consistency with other rules

Consistency with other rules feels correct. It proves that Standard has a well-defined purpose and that the rules follow this purpose. It also helps remember what the style is, because rules "support each other" and it all kind of "connects" in the mind. That's the way I see it.

So, are there any rules in Standard that we can derive an underlying principle upon which to base this decision?

### [`"comma-dangle": [2, "never"]`](http://eslint.org/docs/rules/comma-dangle#never)

I'm guessing that if IE8 and below didn't die on trailing commas, then trailing commas would have been widespread in JavaScript long, long ago.
There is a [proposal for trailing commas in function parameters](https://github.com/tc39/proposal-trailing-function-commas).
So I'm also guessing that Standard will move in the future to trailing commas everywhere. Speculations aside, this is most likely not about minimalism, but browser support.

### [`"curly": [2, "multi-line"]`](http://eslint.org/docs/rules/curly#multi-line)

Minimal over simple. Avoid unnecessary braces, yet, prevent confusion. Allow neat one-liners.

### [`"eqeqeq": [2, "allow-null"]`](http://eslint.org/docs/rules/eqeqeq#allow-null)

This may seem about simplicity, but I don't think so. I think that this is about preventing coercion related bugs.

### [`"semi": [2, "never"]`](http://eslint.org/docs/rules/semi#never)

Minimal over simple. Perhaps at the heart of Standard.

### Conclusion on minimal vs simple

I've found that this is a question of *minimal* vs *simple*, where *minimal* is sans-parens and *simple* is always parens. The general winds in Standard are blowing towards *minimalism*. And, personally, I like that.

In Standard, Mr. *minimal* seems to win, yet, with consideration to important things, such as preventing bugs. So, disallowing parens around the single argument of an arrow function seems consistent with other Standard rules, to me.

## Recap

* Long conversation
* Let's postpone decision between `_ => {}` and `() => {}`
* No-parens seems consistent with other rules
* I find no compelling arguments towards requiring parens other than "it is easier for me to read".

**Comment by feross** [comment]
@mightyiam Thanks for the writeup.

The more I think about this, the more I like `"as-needed", { "requireForBlockBody": true }`.

```js
// bad
[1, 2, 3].map((x) => x * x)

// good
[1, 2, 3].map(x => x * x)

// good
[1, 2, 3].map(number => (
  `A long string with the ${number}. It’s so long that we don’t want it to take up space on the .map line!`
))

// bad
[1, 2, 3].map(x => {
  const y = x + 1
  return x * y
})

// good
[1, 2, 3].map((x) => {
  const y = x + 1
  return x * y
})
```

Minimalist and practical.

**Comment by dcousens** [comment]
@feross I'm happy with all of the above except:

```
// good
[1, 2, 3].map(number => (
  `A long string with the ${number}. It’s so long that we don’t want it to take up space on the .map line!`
))
```

We don't make that exception for:

```
if (cond)
   really long expression
```

Why would we for the lambdas?

**Comment by dcousens** [comment]
I also have cases where I have maybe 50-event handling lambda functions in a row:

``` js
emitter.on('event', () => console.log('...'))
emitter.on('event', () => console.log('...'))

**Comment by mightyiam** [comment]
I wouldn't mind `requireForBlockBody`. It kind of makes sense for me, as well.

@dcousens those 50 event handling lambda functions seem like they could be made with iteration.

Also, you could `eslint-disable arrow-parens` for that block to be consistent. That would make more sense to me. Edge cases be edge cases.

**Comment by dcousens** [comment]
> @dcousens those 50 event handling lambda functions seem like they could be made with iteration.

They aren't exactly like that,  its an example.  The events and the emitters are all completely variable.

**Comment by mightyiam** [comment]
I've added `{ "requireForBlockBody": true }` to the branch of this pull request. I assume that the reason for it not showing up in this pull request, is that it is closed.

**Comment by feross** [comment]
@dcousens Pretty sure that you would be able to keep those single-line lambdas. The given example: 

```js
[1, 2, 3].map(number => (
  `A long string with the ${number}. It’s so long that we don’t want it to take up space on the .map line!`
))
```

was just illustrating that you're allowed to omit the parens if you're doing `number => ()` but not if you're doing `number => {}`.

**Comment by dcousens** [comment]
@feross it turns out I was lying,  I just looked back at the code I was actually referring to... and I use `as-needed` there already.

:confused:

**Comment by yoshuawuyts** [comment]
Can we not do this? - imo when we decided to move away from having parens
on "always" in https://github.com/feross/standard/issues/414 we gave up on
having this rule be consistent. Instead what's being proposed now is
complicated; if we're gonna make a change (and I'm not saying we should)
let's take the sane route and optimize again for readability and
refactoring rather than writability and cleverness.

I propose we do nothing; things are fine as they are.

**Comment by mightyiam** [comment]
@yoshuawuyts will you please explain what the issue with "as-needed" and refactoring is?

Is it that when adding a second argument to a single argument arrow function you'd have to add parens? I agree that's no optimal for refactoring. Yet, it does not seem to be a good enough reason to not allow absence of parens in single argument arrow functions. That's my take.

**Pull request closed without merging**
