### PR TITLE
Fix indent rule to use eslint 1.0.0 SwitchCase option

### PR DESCRIPTION
**Pull request by NassarS**
Fixes https://github.com/feross/eslint-config-standard/issues/6

### CODE REVIEW

**Comment by NassarS** [comment]
I didn't bump the es-lint version from 1.0.0-rc-1 to 1.0.0 in the PR. You will also want to do that before launching a new version.

**Comment by listepo** [comment]
+1

**Comment by Flet** [comment]
We'll need an `npm version prerelease && npm publish` from @feross to get this out there :)

**Comment by feross** [comment]
This is fixed! 4.0.0 is released.

**Pull request merged**
