### PR TITLE
Enforce balanced block comments

### PR DESCRIPTION
**Pull request by feross**
See https://github.com/feross/standard/issues/572

### CODE REVIEW

**Comment by dcousens** [comment]
ACK

**Comment by yisibl** [comment]
```bash
node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^
Error: standard:
       	Configuration for rule "spaced-comment" is invalid:
       	Value "data["1"].block.balanced" has additional properties.
```

**Comment by feross** [comment]
@yisibl Upgrade your eslint version.

**Comment by yisibl** [comment]
@feross Thanks!

**Pull request merged**
