### PR TITLE
Add as-needed arrow-parens rule.

### PR DESCRIPTION
**Pull request by KevinGrandon**
As discussed in: https://github.com/feross/standard/issues/309

I wanted to run some tests with this so I thought might as well submit a PR.

### CODE REVIEW

**Comment by dcousens** [comment]
This hasn't run against all the repositories.

**Comment by KevinGrandon** [comment]
I think I ran this rule, discussing over in the issue: https://github.com/feross/standard/issues/309#issuecomment-151331883

**Comment by dcousens** [comment]
:+1: , just pointing out that test doesn't run here is all.

**Comment by feross** [comment]
Thanks for the PR, we ended up merging https://github.com/feross/eslint-config-standard/commit/dd85d36d41530deac9c6036f79116f9e21966235

**Comment by mightyiam** [comment]
I've [wrote some more thoughts](https://github.com/feross/eslint-config-standard/pull/54#issuecomment-262828198) regarding this in my PR, suggesting `"arrow-parens": [2, "as-needed"]`. If you care, please check it out.

**Pull request closed without merging**
