### PR TITLE
no-unused-expressions

### PR DESCRIPTION
**Pull request by dcousens**
Ref http://eslint.org/docs/rules/no-unused-expressions

Related https://github.com/eslint/eslint/issues/7642#issuecomment-262657432
https://github.com/feross/standard/issues/690

### CODE REVIEW

**Comment by feross** [comment]
Going to hold off on merging until v9.

**Comment by dcousens** [comment]
No worries :+1:

**Comment by feross** [comment]
Sorry, didn't see this PR. I already added this rule in commit https://github.com/feross/eslint-config-standard/commit/1e3975cffaea7a444cd13914afab93c5942599bb

**Comment by dcousens** [comment]
No worries :)

**Pull request closed without merging**
