### PR TITLE
eslint-plugin-ava with recommended rules

### PR DESCRIPTION
**Pull request by mightyiam**
https://github.com/avajs/eslint-plugin-ava

### CODE REVIEW

**Comment by julien-f** [comment]
Not everyone uses AVA, why would it makes sense to include it by default?

**Comment by mightyiam** [comment]
[The AVA plugin seems to have 24 rules](https://github.com/avajs/eslint-plugin-ava#rules).

[These seem to be the recommended rules for v4.0.0](https://github.com/avajs/eslint-plugin-ava/blob/v4.0.0/index.js#L15-L39).

All 24 existing rules are configured in some way.

Below are the recommended rules and my thoughts whether they should be included in JS Standard Style.

- [assertion-arguments](docs/rules/assertion-arguments.md) - Enforce passing correct arguments to assertions.
  `'error'`
  Seems to be always helpful.
- [max-asserts](docs/rules/max-asserts.md) - Limit the number of assertions in a test.
  `['off', 5]`
  Proper for standard, which doesn't seem to allow exceptions.
- [no-async-fn-without-await](docs/rules/no-async-fn-without-await.md) - Ensure that async tests use `await`.
  `'error'`
  Why not?
- [no-cb-test](docs/rules/no-cb-test.md) - Ensure no `test.cb()` is used.
  `'error'`
  Same as above. Why not force async-await?
- [no-duplicate-modifiers](docs/rules/no-duplicate-modifiers.md) - Ensure tests do not have duplicate modifiers.
  `'error'`
  Seems to be always helpful.
- [no-identical-title](docs/rules/no-identical-title.md) - Ensure no tests have the same title.
  `'error'`
  It seems to [not flag computed titles](https://github.com/avajs/eslint-plugin-ava/blob/v4.0.0/rules/no-identical-title.js#L35). Seems always correct.
- [no-ignored-test-files](docs/rules/no-ignored-test-files.md) - Ensure no tests are written in ignored files.
  `'error'`
  :question: Seems to be incredibly valuable in helping make sure that your tests are actually being executed. I'm trying to think of a "legitimate" scenario where there are AVA tests in the repository while the AVA configuration excludes them. There might be but I couldn't think of anything. Any ideas? I'm assuming very rare.
- [no-invalid-end](docs/rules/no-invalid-end.md) - Ensure `t.end()` is only called inside `test.cb()`.
  `'error'`
  Seems to be always helpful.
- [no-nested-tests](docs/rules/no-nested-tests.md) - Ensure no tests are nested.
  `'error'`
  Seems to be always helpful.
- [no-only-test](docs/rules/no-only-test.md) - Ensure no `test.only()` are present.
  `'error'`
  Seems to be always very helpful.
- [no-skip-assert](docs/rules/no-skip-assert.md) - Ensure no assertions are skipped.
  `'error'`
  Seems to be always helpful.
- [no-skip-test](docs/rules/no-skip-test.md) - Ensure no tests are skipped.
  `'error'`
  Seems to be always helpful.
- [no-statement-after-end](docs/rules/no-statement-after-end.md) - Ensure `t.end()` is the last statement executed.
  `'error'`
  Seems to be always helpful.
- [no-todo-implementation](docs/rules/no-todo-implementation.md) - Ensure `test.todo()` is not given an implementation function.
  `'error'`
  Seems to be always helpful.
- [no-todo-test](docs/rules/no-todo-test.md) - Ensure no `test.todo()` is used.
  `'warn'`
  :question: May not be appropriate for JS Standard Style. I don't remember seeing any warnings from JS Standard style before. If warnings are inappropriate in JS Standard Style, then I would turn this off.
- [no-unknown-modifiers](docs/rules/no-unknown-modifiers.md) - Prevent the use of unknown test modifiers.
  `'error'`
  :question: If someone wishes his own test modifier to use his own fork of AVA, then perhaps he will extend this will to use his own linting configuration?
- [prefer-async-await](docs/rules/prefer-async-await.md) - Prefer using async/await instead of returning a Promise.
  `'error'`
  :question: I tend to agree. async-await was created to simplify flow better than promises. Yet, I personally do not have enough experience to decide for everyone.
- [prefer-power-assert](docs/rules/prefer-power-assert.md) - Allow only use of the asserts that have no [power-assert](https://github.com/power-assert-js/power-assert) alternative.
  `'off'`
  Yes. This should not be enforced.
- [test-ended](docs/rules/test-ended.md) - Ensure callback tests are explicitly ended.
  `'error'`
  Seems to be redundant when we have no-cb-test. Doesn't hurt.
- [test-title](docs/rules/test-title.md) - Ensure tests have a title.
  `['error', 'if-multiple']`
  Seems to be reasonable to me.
- [use-t-well](docs/rules/use-t-well.md) - Prevent the incorrect use of `t`.
  `'error'`
  Probably always helpful.
- [use-t](docs/rules/use-t.md) - Ensure test functions use `t` as their parameter.
  `'error'`
  Seems always helpful.
- [use-test](docs/rules/use-test.md) - Ensure that AVA is imported with `test` as the variable name.
  `'error'`
  Seems always helpful.
- [use-true-false](docs/rules/use-true-false.md) - Ensure that `t.true()`/`t.false()` are used instead of `t.truthy()`/`t.falsy()`.
  `'error'`
  Seems to be in-line with JavaScript Standard Style.

@sindresorhus, I imagine that you adhere to SemVer—a change to the recommended rules will mean a major version bump—correct me if I'm wrong.

Do you have any tips on this, @sindresorhus?

**Comment by mightyiam** [comment]
I don't have a clue why the test fails. I'm trying to reproduce locally with the same versions of Node.js and npm and it passes.

**Comment by mightyiam** [comment]
I'm assuming that the failing test is the ESLint CLIEngine test. I still don't know why it fails in CI and not locally for me.

**Comment by sindresorhus** [comment]
> Not everyone uses AVA, why would it makes sense to include it by default?

The rules are only applied to AVA test files, but I agree, doesn't make much sense to include here.

> I imagine that you adhere to SemVer—a change to the recommended rules will mean a major version bump—correct me if I'm wrong.

Yes

**Comment by feross** [comment]
AVA is cool. But we can't add rules for a specific library like this or `standard` would quickly become bloated. We actually removed React-specific rules in a previous version.

Thanks for the thoughtful PR, though.

**Pull request closed without merging**
