### PR TITLE
Support for eslint v3.0.0

### PR DESCRIPTION
**Pull request by simonkberg**

### CODE REVIEW

**Comment by unindented** [comment]
@feross any chance to get this merged and published soonish?

**Comment by dcousens** [comment]
LGTM,  happy to merge if you are @feross

**Comment by simonkberg** [comment]
Also, same change here:
https://github.com/feross/eslint-config-standard-react/pull/26
https://github.com/feross/eslint-config-standard-jsx/pull/7

**Comment by dcousens** [comment]
@unindented could you update all the relevant repos such that travis tests both then?
Also, any reason not to just bump to `3.0.0` entirely?

**Comment by unindented** [comment]
It looks like @simonkberg already did all the work.

Things seem to work fine with both `2.x` and `3.x`, so you probably don't want to force people to upgrade to `3.x` unnecessarily. I'm guessing that's why @simonkberg kept both.

**Comment by simonkberg** [comment]
Well there's no test for eslint 3, as I'm not sure how a test for both versions would work. But yeah, the intention is to not require a major version bump. But i could update the PRs to use eslint 3 entirely if that's the way you want to go

**Comment by simonkberg** [comment]
These are the breaking changes in v3.0.0:

* Breaking: Add `require-yield` rule to `eslint:recommended` (fixes eslint/eslint#6550) (eslint/eslint#6554)
* Breaking: Error thrown/printed if no config found (fixes eslint/eslint#5987) (eslint/eslint#6538)
* Breaking: Update eslint:recommended (fixes eslint/eslint#6403) (eslint/eslint#6509)
* Breaking: Drop support for node < 4 (fixes eslint/eslint#4483) (eslint/eslint#6401)
* Breaking: use default for complexity in eslint:recommended (fixes eslint/eslint#6021) (eslint/eslint#6410)

**Comment by simonkberg** [comment]
Now that I think about it, something like this should work in travis:
```yml
script:
   - npm test
   - npm i -D eslint@^3.0.0
   - npm test
```
Assuming we keep `eslint@^2.9.0` as the dev dependency.

**Comment by dcousens** [comment]
Have you run the tests against the majority of repos using standard?  You'll be able to test the impact it will have on users there.
I don't think upgrading users to `3.0.0` is an issue... at least not one that I have.

**Comment by simonkberg** [comment]
@dcousens hm, that would be a separate pr to the [standard](https://github.com/feross/standard) package (can't really test the impact from here). 

A full version bump would make sense in the `standard`-package as it ships eslint as a direct dependency, while for anyone extending the shareable configs it would result in confusing `UNMET PEER DEPENDENCY` errors. It might not be very obvious they have to update their own dependency of eslint to v3 - at least without providing a deprecation notice beforehand.

If we ship this config with support for both `^2.9.0` and `^3.0.0` we won't break backward compatibility for anyone extending this config, and we can then test the full impact of upgrading eslint to v3 in `standard` separately. Since adding support for another version range in the peer dependencies doesn't break any backward compatibility it should be very safe.

**Comment by briancavalier** [comment]
As a user of eslint-config-standard who is currently blocked from updating several projects (work and personal) to eslint 3.x, the change to support 2.9 and 3 peerDeps seems like a helpful change that would unblock me (and probably others).

I realize there may be reasons for not merging it, but it wasn't clear what they might be from reading this thread.  Is there anything I could help with (testing?) in order to get this merged?

**Comment by unindented** [comment]
@dcousens @feross would you mind reviewing and merging @simonkberg's PRs?

**Comment by dcousens** [comment]
I'm going to defer this one to @feross,  as he might have further context knowledge on this that I'm not aware of.
Otherwise,  I'm +1 and happy to merge.

**Comment by feross** [comment]
Sorry for the delay in merging, folks! I was taking a break from open source for two weeks (https://twitter.com/feross/status/747981655504105473).

Thanks for your patience, everyone. 😄 Thanks for the PR, @simonkberg.

This is released as 5.3.2.

**Comment by unindented** [comment]
Thank you @feross! It's easy to forget how much pressure we put on owners of open-source projects. Much respect.

**Pull request merged**
