### PR TITLE
Changed rule for no-labels to conform to eslint@1.10.3 requirement

### PR DESCRIPTION
**Pull request by oliverturner**
Minimal change for conformance

### CODE REVIEW

**Comment by joefitzgerald** [comment]
:+1: Can't update to `eslint-config-standard` `v5.0.0` without this.

**Comment by feross** [comment]
`eslint-config-standard` v5.0.0 is designed for use with `eslint` v2.0.0, which is due to be released soon.

Try updating eslint: `npm install eslint@2.0.0-rc.0`

**Comment by oliverturner** [comment]
Yeah... apologies for that: only realised late last night that this was what was needed.

**Comment by joefitzgerald** [comment]
@feross perhaps you should have used a pre-release version given that eslint 2.0.0 is still ore-release (rc0 currently)? Thanks for the context though!

Are there release notes somewhere, where you can convey this information to us?

**Comment by feross** [comment]
@joefitzgerald Yep, a prerelease version would have been ideal. Next time!

`standard` itself has a CHANGELOG. For this repo, I'd just check the commit log. [Here's](https://github.com/feross/eslint-config-standard/commit/93962cd075367efaa103f7f98a649d2482bf24a2) the relevant commit.

**Pull request closed without merging**
